// Local fallback list mirrored from app/util/side_effect_terms.py
// Includes canonical labels plus a few common user-facing aliases.
export const COMMON_SYMPTOMS: string[] = Array.from(
  new Set([
    // Canonical labels from server
    "nausea",
    "vomiting",
    "diarrhea",
    "constipation",
    "abdominal pain",
    "abdominal discomfort",
    "indigestion",
    "heartburn",
    "decreased appetite",
    "dry mouth",
    "bloating",
    "gas",
    "nausea and vomiting",
    "gastrointestinal disorder",
    "colitis",
    "rectal bleeding",
    "difficulty swallowing",
    "mouth ulcers",
    "pancreatitis",
    "increased appetite",

    "headache",
    "dizziness",
    "drowsiness",
    "insomnia",
    "fatigue",
    "weakness",
    "tremor",
    "confusion",
    "anxiety",
    "depression",
    "irritability",
    "memory problems",
    "numbness",
    "hallucinations",
    "suicidal thoughts",
    "mood changes",
    "concentration problems",
    "coordination problems",
    "speech problems",
    "feeling abnormal",
    "ear ringing",
    "cognitive impairment",
    "dark urine",

    "rash",
    "itching",
    "hives",
    "skin irritation",
    "skin redness",
    "dry skin",
    "skin peeling",
    "blisters",
    "swelling",
    "facial swelling",
    "bruising",
    "sun sensitivity",
    "acne",
    "skin darkening",
    "night sweats",
    "stevens-johnson syndrome",
    "skin infection",
    "nail changes",

    "cough",
    "shortness of breath",
    "nasal congestion",
    "runny nose",
    "sore throat",
    "common cold",
    "sinus pain",
    "wheezing",
    "hoarseness",
    "nosebleed",
    "pneumonia",
    "blood clot in lung",
    "throat discomfort",

    "chest pain",
    "back pain",
    "joint pain",
    "muscle pain",
    "pain in extremity",
    "muscle spasms",
    "joint swelling",
    "injection site pain",
    "injection site redness",
    "neck pain",
    "bone pain",
    "tendon pain",
    "stiffness",
    "fibromyalgia",
    "muscle breakdown",

    "rapid heartbeat",
    "high blood pressure",
    "low blood pressure",
    "fever",
    "chills",
    "dehydration",
    "hot flash",
    "excessive sweating",
    "irregular heartbeat",
    "heart failure",
    "blood clot",
    "stroke",
    "heart attack",
    "low sodium",
    "low potassium",
    "low magnesium",
    "high potassium",
    "elevated liver enzymes",
    "elevated creatinine",
    "liver damage",
    "kidney problems",
    "low blood counts",

    "urinary tract infection",
    "frequent urination",
    "painful urination",
    "vaginal discharge",
    "urinary retention",
    "urinary incontinence",
    "kidney infection",
    "blood in urine",
    "erectile dysfunction",
    "menstrual irregularities",
    "yeast infection",
    "bloodstream infection",

    "blurred vision",
    "visual impairment",
    "eye irritation",
    "eye redness",
    "dry eyes",
    "double vision",
    "sensitivity to light",
    "cataracts",
    "glaucoma",

    "hair loss",
    "weight loss",
    "weight gain",
    "hair growth",

    "allergic reaction",
    "seizure",
    "loss of consciousness",
    "infection",
    "red blood cell count decreased",
    "low white blood cells",
    "high blood sugar",
    "low blood sugar",
    "thyroid problems",
    "swollen lymph nodes",
    "drug reaction",

    "paranoia",
    "bipolar episode",
    "panic attacks",
    "emotional disturbance",
    "aggression",
    "nightmares",
    "apathy",
    "restless legs",
    "euphoria",

    "increased thirst",
    "increased hunger",
    "excessive urination",
    "bone density decreased",
    "adrenal suppression",
    "cushingoid features",
    "gout",

    "lupus-like reaction",
    "blood vessel inflammation",
    "lung inflammation",
    "inflammatory reaction",

    "black or bloody stools",
    "feeling faint",
    "slurred speech",
    "weakness in a part of body",
    "leg swelling",
    "yellowing of skin or eyes",
    "unusual bruising or bleeding",
    "severe headache",

    // Helpful user-facing aliases / legacy search terms
    "loss of appetite",
    "lightheadedness",
    "tingling",
    "pins and needles",
    "palpitations",
    "sweating",
    "stuffy nose",
    "acid reflux",
    "migraine",
    "body aches",
    "vertigo",
    "brain fog",
    "tiredness",
    "lightheadedness",
    "restlessness",
    "night sweats",
    "weight changes",
    "hair changes",
    "easy bruising",
    "frequent infections",
    "easy bleeding",
    "feeling hot",
    "feeling cold",
    "feeling weak",
    "feeling tired",
    "feeling dizzy",
    "feeling lightheaded",
    "feeling drowsy",
    "feeling anxious",
    "feeling depressed",
    "feeling irritable",
    "feeling confused",
    "feeling restless",
    "feeling euphoric",


  ])
).sort((a, b) => a.localeCompare(b));